name: Auto Update OS Versions

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python generate_os_versions.py

      - name: Commit updated CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add os_versions.csv highlighted_os_versions.csv
          git commit -m "Auto-update OS versions CSV" || echo "No changes to commit"
          git push

      - name: Send email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Daily OS Release Report – ${{ github.run_id }}"
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ secrets.MAIL_TO }}
          html_body: |
            <p>Hello 👋,</p>
            <p>Here are today's OS version updates (⚠️ = changed since last run):</p>
            <pre>
            $(cat highlighted_os_versions.csv)
            </pre>
            <p>Best,<br>GitHub Actions Bot</p>
          attachments: os_versions.csv

