name: Auto Update OS Versions (Debug)

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install requests beautifulsoup4

      - name: Run script (with debug)
        run: |
          set -e
          echo "Running scraper..."
          python generate_os_versions.py || (echo "Python script failed" && exit 1)
          echo "Files after run:"
          ls -lh

      - name: Show CSV preview
        run: |
          echo "=== os_versions.csv (first 20 lines) ==="
          head -20 os_versions.csv || echo "No os_versions.csv found"
          echo "=== highlighted_os_versions.csv (first 20 lines) ==="
          head -20 highlighted_os_versions.csv || echo "No highlighted_os_versions.csv found"

      - name: Commit updated CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add os_versions.csv highlighted_os_versions.csv
          git commit -m "Auto-update OS versions CSV" || echo "No changes to commit"
          git push
